FROM python:3.6-alpine

COPY requirements.txt /code/
WORKDIR /code
RUN pip install -r requirements.txt

COPY service/*.py /code/service/

ENV FLASK_APP service/app.py

CMD ["flask", "run", "--host=0.0.0.0"]
